### ISSUE TITLE
artifactory-maven-plugin-example issues

### ISSUE THREAD

**Issue by colathurv** [jfrog/artifactory-maven-plugin#10]
I found 2 issues when working with the example on the title of this issue. 
For each of them, I have attached a UI Snapshot.
**Issue 1:** In order to make the example work, I had to modify the parent pom to add the following to properties, else it will not even compile.
`<maven.compiler.source>1.7</maven.compiler.source>
  <maven.compiler.target>1.7</maven.compiler.target>`

**Issue 2:** Running the example twice i.e., pushing the same artifact (making no changes to anything) to a Maven Repository, is creating 2 wars, but with different checksums. This is a little non-intuitive, considering I have not changed 
anything.

Images are as follows, in the same order as issues.

<img width="572" alt="Screen Shot 2021-01-26 at 7 06 00 PM" src="https://user-images.githubusercontent.com/6411605/105937043-9d011c80-6009-11eb-9fe2-f1317e14df00.png">
<img width="866" alt="Screen Shot 2021-01-26 at 7 08 19 PM" src="https://user-images.githubusercontent.com/6411605/105937188-e487a880-6009-11eb-821e-3950dc859d09.png">

**Comment by yahavi** [comment]
@colathurv,
Thanks for reporting this issue.

---

> Issue 1: In order to make the example work, I had to modify the parent pom to add the following to properties, else it will not even compile.

This error came from the maven-compiler-plugin. It looks like your Maven version is old enough so it chooses Java 5 by default. I could reproduce this error with Maven 3.3.9. I created https://github.com/jfrog/project-examples/pull/253 to overcome this type of error in the example.

---

> Issue 2: Running the example twice i.e., pushing the same artifact (making no changes to anything) to a Maven Repository, is creating 2 wars, but with different checksums. This is a little non-intuitive, considering I have not changed
anything.

This is the default Maven behavior. Maven puts timestamps in the Jars and therefore the builds, by default, are not reproducible. In order to make them reproducible and remove the timestamps, I'd recommend using the [Configuring for Reproducible Builds](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) guild.
